<?php

namespace Database\Seeders;

use App\Models\Base\Info\Measure;
use App\Models\Base\Products\Product;
use App\Models\Site\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $measureKg = Measure::query()->where('name_uz', 'Kilogram')->first();
        $measureShT = Measure::query()->where('name_uz', 'Dona')->first();

        $category = Category::query()->where('name_uz', 'Зелень')->first();
        $data = [
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureShT->id,
                'slug' => 'перец-острый-1шт',
                'name_ru' => 'Перец острый, 1шт',
                'name_uz' => 'Перец острый, 1шт',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 1000,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureShT->id,
                'slug' => 'листья-салата-лолло-росса-пучок',
                'name_ru' => 'Листья салата Лолло росса, пучок',
                'name_uz' => 'Листья салата Лолло росса, пучок',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 2000,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureShT->id,
                'slug' => 'лук-зеленый-барашка-пучок',
                'name_ru' => 'Лук зеленый барашка, пучок',
                'name_uz' => 'Лук зеленый барашка, пучок',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 5000,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureShT->id,
                'slug' => 'мята-пучок',
                'name_ru' => 'Мята, пучок',
                'name_uz' => 'Мята, пучок',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 3300,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureShT->id,
                'slug' => 'руккола-пучок',
                'name_ru' => 'Руккола, пучок',
                'name_uz' => 'Руккола, пучок',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 4400,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureShT->id,
                'slug' => 'райхан-Базилик-зеленый-пучок',
                'name_ru' => 'Райхан (Базилик) зеленый, пучок',
                'name_uz' => 'Райхан (Базилик) зеленый, пучок',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 2000,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ]
        ];
        DB::table('products')->insert($data);

        $category = Category::query()->where('name_uz', 'Овощи')->first();
        $data = [
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'болгарский-перец-местный-кг',
                'name_ru' => 'Болгарский перец местный кг',
                'name_uz' => 'Болгарский перец местный кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 2300,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'помидоры-розовые-кг',
                'name_ru' => 'Помидоры розовые, кг',
                'name_uz' => 'Помидоры розовые, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 5500,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'лук-красный-кг',
                'name_ru' => 'Лук красный, кг',
                'name_uz' => 'Лук красный, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 10000,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'огурцы-орзу-кг',
                'name_ru' => 'Огурцы Орзу, кг',
                'name_uz' => 'Огурцы Орзу, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 5175,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureShT->id,
                'slug' => 'айсберг-вилок-шт',
                'name_ru' => 'Айсберг вилок, шт',
                'name_uz' => 'Айсберг вилок, шт',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 8000,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'картофель-молодой-кг',
                'name_ru' => 'Картофель молодой, кг',
                'name_uz' => 'Картофель молодой, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 3200,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ]
        ];
        DB::table('products')->insert($data);

        $category = Category::query()->where('name_uz', 'Фрукты и ягоды')->first();
        $data = [
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'яблоко-салтанат-кг',
                'name_ru' => 'Яблоко Салтанат, кг',
                'name_uz' => 'Яблоко Салтанат, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 32000,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'помидоры-розовые-кг',
                'name_ru' => 'Помидоры розовые, кг',
                'name_uz' => 'Помидоры розовые, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 5500,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'лимон-местный-кг',
                'name_ru' => 'Лимон местный, кг',
                'name_uz' => 'Лимон местный, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 15680,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'яблоко-симиренко-кг',
                'name_ru' => 'Яблоко Симиренко, кг',
                'name_uz' => 'Яблоко Симиренко, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 13500,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'апельсин-египет-кг',
                'name_ru' => 'Апельсин Египет, кг',
                'name_uz' => 'Апельсин Египет, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 8000,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ],
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'банан-кг',
                'name_ru' => 'Банан, кг',
                'name_uz' => 'Банан, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 18480,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ]
        ];
        DB::table('products')->insert($data);

        $category = Category::query()->where('name_uz', 'Сухофрукты')->first();
        $data = [
            [
                'category_id' => $category->id,
                'brand_id' => 1,
                'measure_id' => $measureKg->id,
                'slug' => 'финики-отборные-кг',
                'name_ru' => 'Финики отборные, кг',
                'name_uz' => 'Финики отборные, кг',
                'sku' => rand(10000, 99999),
                'unicode' => \Str::random(8),
                'price' => 170000,
                'old_price' => null,
                'stock' => 10,
                'info_ru' => null,
                'info_uz' => null,
                'status' => 10,
                'created_at' => now(),
            ]
        ];
        DB::table('products')->insert($data);
    }

}
